# Generated by Django 4.2.30 on 2026-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='1-Necklace-RG.webp', help_text='Upload product image', upload_to=''),
        ),
    ]
